### ISSUE TITLE
Changing the min-height on the outer div

### ISSUE THREAD

**Issue by mrunks** [LayTec-AG/Plotly.Blazor#165]
After setting the height and width in the layout I notice that when a bar chart renders that a min-height of 350px is set. 

The element looks like the following upon inspecting HTML

<div style="min-height: 350px; height: 100%"  id="SampleChart" class="js-plotly-plot">  

The chart itself seems to render the correct height but then there is a ton of white space even after shrinking the margins.  Is there a way to override that setting ?

**Comment by TheCakeMonster** [comment]
I was wondering this too, as this is causing me a problem.

I think overriding this value will be extremely hard, as styles applied directly to a container through HTML have precedence over almost everything else. Ideally this should be parameterised so that it can be modified where necessary.

@mrunks Did you manage to find a workaround for this?

**Comment by sean-mcl** [comment]
I could make it a additional variable if you guys need it

**Comment by TheCakeMonster** [comment]
Yes that would be very useful. 

Defaulting the value to the current setting should avoid anyone suffering any breaking changes. Making this a parameter allows greater flexibility for anyone who needs to create charts that are smaller than this minimum, which is the situation for the usage I am trying.

**Comment by sean-mcl** [comment]
I must have misunderstood the problem at this time.

Just overwrite the style attribute using

`<PlotlyChart style="<custom>"/>`

**Comment by sean-mcl** [comment]
For your information, 350px is plotly's default height when no height has been found.  Thats why I've set it to 350px too.
