### ISSUE TITLE
Config option DisplayModeBar is not adhered to

### ISSUE THREAD

**Issue by EuanKirkhope** [LayTec-AG/Plotly.Blazor#34]
The mode bar will always appear in hover mode (the default action).

```
    Config config = new Config
    {
        DisplayModeBar = ConfigLib.DisplayModeBarEnum.True
    };
```

Setting to False has no effect.

https://plotly.com/javascript/configuration-options/#never-display-the-modebar

Changing Config.cs DisplayModeBar def to below fixes issue:

```
public bool? DisplayModeBar { get; set; }
```

**Comment by sean-mcleish** [comment]
Hi,

thank you for the hint. I'll fix it. 👍

**Comment by sean-mcleish** [comment]
Just took a look at the whole thing.
We can't use bools here because there are three different possibilities: hover, true, false. According to the ([plotly scheme](https://raw.githubusercontent.com/plotly/plotly.js/master/dist/plot-schema.json)), this is an enum.

He recognizes "true" with quotes as valid but ignores "false". According to the plotly scheme these are both valid values.

I will forward the problem to the plotly team.

**Comment by EuanKirkhope** [comment]
Yeah I see that in the code.  Defining as bool works though, but you can't change back to hover after defining the item.  If it is left undefined its hover, and if you define the variable its either on or off.  I don't think many would want to dynamically change back from either behaviours to hover.  Will be good to see what the Plotly folks say.  

Very nice wrapper Btw.   Sure beats my method which was to define the json as as string and send to plotly through the interop.   Thankyou!

**Comment by sean-mcleish** [comment]
Hi, 
should work now in v1.1.4
